/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Default main class (can be overridden with -Pmain=...)
    mainClass = project.findProperty("main") as String? ?: "playground.modern.ModernMain"
}

// Task to run the Modern (Route A) main class
tasks.register<JavaExec>("runModern") {
    group = "application"
    description = "Run the Modern Java Approaches demo (Route A)"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("playground.modern.ModernMain")
}

// Task to run the JDK25 (Route B) main class
tasks.register<JavaExec>("runJdk25") {
    group = "application"
    description = "Run the Java 25 Features demo (Route B)"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("playground.jdk25.Jdk25Main")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
